version: '3.8'

services:
  frontend:
    env_file:
      - .env.production
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  backend:
    env_file:
      - .env.production
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - MONGO_URL=${DB_URL}  # 这里使用你 .env 文件中的 DB_URL
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
